Sistema_Camaronera/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from app_login.views.login import loginFormView
from app_template.views.template import IndexView

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', IndexView.as_view(),name='inicio_dashboard'),
    path('login/', include('app_login.urls')),
    path('inventario/', include('app_inventario.app_categoria.urls')),
    path('stock/', include('app_stock.app_detalle_stock.urls')),
    path('stock_directo/', include('app_stock_directo.urls')),
    path('empresa/', include('app_empresa.app_reg_empresa.urls')),
    path('dieta/', include('app_dieta.app_dieta_reg.urls')),
    path('seguimiento/', include('app_seglineal.app_seguimiento.urls')),
    path('factura/', include('app_factura_detalle.urls')),
    path('usuario/', include('app_user.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_inventario/app_categoria/urls.py
from django.urls import path
from .views.categoria import *
from .views.producto import *

app_name = 'app_categoria'

urlpatterns = [
   # muestrame esa vista
    path('categoria/crear/', crearCategoriaView.as_view(), name='crear_categoria'),
    path('categoria/actualizar/<int:pk>/', actualizarCategoriaView.as_view(), name='actualizar_categoria'),
    path('categoria/eliminar/<int:pk>/', eliminarCategoriaView.as_view(), name='eliminar_categoria'),
    path('categoria/listar/', listarCategoriaView.as_view(), name='listar_categoria'),

    path('producto/crear/', crearProductoView.as_view(), name='crear_producto'),
    path('producto/actualizar/<int:pk>/', actualizarProductoView.as_view(), name='actualizar_producto'),
    path('producto/eliminar/<int:pk>/', eliminarProductoView.as_view(), name='eliminar_producto'),
    path('producto/listar/', listarProductoView.as_view(), name='listar_producto')

]

app_user/urls.py
from django.urls import path
from .views.user import *

app_name = 'app_usuario'

urlpatterns = [

    path('usuario/crear/', crearUsuarioView.as_view(), name='crear_usuario'),
    path('usuario/actualizar/<int:pk>/', actualizarUsuarioView.as_view(), name='actualizar_usuario'),
    path('usuario/eliminar/<int:pk>/', eliminarUsuarioView.as_view(), name='eliminar_usuario'),
    path('usuario/listar/', listarUsuarioView.as_view(), name='listar_usuario')
]

app_inventario/app_categoria/models.py
from crum import get_current_user
from django.db import models
from django.forms import model_to_dict
# Create your models here.
from Sistema_Camaronera.settings import MEDIA_URL, STATIC_URL
# from app_auditoria.models import BaseModel
from app_empresa.app_reg_empresa.models import Empresa
from django.db import connection


class Categoria(models.Model):
    nombre = models.CharField(max_length=150, verbose_name='Nombre', unique=True)
    descripcion = models.CharField(max_length=400, verbose_name='Descripcion')

    def __str__(self):
        return self.nombre

    # def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
    #     user = get_current_user()
    #     if user is not None:
    #         if not self.pk:
    #             self.user_creador = user
    #         else:
    #             self.user_actualizo = user
    #     super(Categoria,self).save()

    def toJSON(self):
        item = model_to_dict(self)
        return item

    class Meta:
        db_table = 'tb_categoria'
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['id']


class Producto(models.Model):
    nombre = models.CharField(max_length=150, verbose_name='Nombre ', unique=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    gramaje = models.CharField(max_length=100, verbose_name='Gramaje ', null=True, blank=True)
    descripcion = models.CharField(max_length=400, verbose_name='Sub-Categoria ', null=True, blank=True)
    presentacion = models.CharField(max_length=400, verbose_name='Presentacion ', null=True, blank=True)  # OJO VER BIEN EN CUENTA
    peso_presentacion = models.DecimalField(max_digits=19, decimal_places=0, verbose_name='Peso de la Presentacion ', null=True, blank=True)  # OJO VER BIEN EN CUENTA
    unid_medida = models.CharField(max_length=400, verbose_name='Unidad de Medida de la Presentación ', null=True, blank=True)  # OJO VER BIEN EN CUENTA
    unid_aplicacion = models.CharField(max_length=400, verbose_name='Aplicación en ', null=True, blank=True)  # OJO VER BIEN EN CUENTA
    minimo_stock = models.DecimalField(max_digits=19, decimal_places=0, verbose_name='Stock Mínimo ', null=True, blank=True)
    costo = models.DecimalField(max_digits=19, decimal_places=10, default=0.0000)
    estado = models.BooleanField(default=True, verbose_name='Estado ')
    aplic_directa = models.BooleanField(default=False, verbose_name='Aplicación Directa ')
    imagen = models.ImageField(upload_to='product/%Y/%m/%d', null=True, blank=True, verbose_name='Seleccionar Imagen ')

    def __str__(self):
        return self.nombre

    def get_unidad_aplicacion(self):
        if self.unid_aplicacion == 'GR':
            return 1000
        elif self.unid_aplicacion == 'KG':
            return 2.2
        elif self.unid_aplicacion == 'LB':
            return 1
        elif self.unid_aplicacion == 'CA':
            return 1
        return 1000

    def get_image(self):
        if self.imagen:
            return '{}{}'.format(MEDIA_URL, self.imagen)
        return '{}{}'.format(STATIC_URL, 'img/empty.png')

    def toJSON(self):
        item = model_to_dict(self)
        item['valor_aplicacion'] = self.get_unidad_aplicacion()
        item['imagen'] = self.get_image()
        item['minimo_stock'] = '0.00' if self.minimo_stock is None else format(self.minimo_stock, '.2f')
        item['peso_presentacion'] = '0.00' if self.peso_presentacion is None else format(self.peso_presentacion, '.2f')
        item['costo'] = format(self.costo, '.2f')
        return item

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        nuevo_producto = super(Producto, self).save()

        empresas = Empresa.objects.filter(estado=True)
        cursor = connection.cursor()

        for empresa in empresas:
            # Validar si el producto-empresa ya existe
            cursor.execute(
                "SELECT nombre_empresa_id, nombre_prod_id FROM stock_total WHERE nombre_empresa_id = %s AND nombre_prod_id = %s;" % (
                empresa.pk, self.id))
            registros = cursor.fetchall()

            if not registros:
                cursor.execute(
                    "INSERT INTO stock_total (nombre_empresa_id, nombre_prod_id, stock) VALUES (%s, %s, 0);" % (
                    empresa.pk, self.id))

        return nuevo_producto

    class Meta:
        db_table = 'tb_producto'
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
        ordering = ['id']

app_inventario/app_producto/models.py
from django.db import models

# Create your models here.

app_inventario/app_categoria/forms.py
from django.forms import *
from app_inventario.app_categoria.models import Categoria

class CategoriaForm(ModelForm):
    class Meta:
        model = Categoria
        fields = '__all__'
        widgets = {
            'nombre': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese un nombre',
                    'autocomplete': 'off'
                }
            ),
            'descripcion': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese una Descripción',
                    'autocomplete': 'off'
                }
            )

        }

        # exclude = ['user_creador', 'user_actualizo']

app_inventario/app_producto/forms.py
from django.forms import *
from app_inventario.app_categoria.models import Producto

OPCIONES_PRESENTACION = (
    ('SACO', 'SACO'),
    ('GALON', 'GALON'),
    ('TACHO', 'TACHO'),
    ('FRASCO', 'FRASCO'),
    ('FUNDA', 'FUNDA'),
    ('CANECA', 'CANECA'),
)

OPCIONES_MEDIDA = (
    ('LB', 'LIBRAS'),
    ('KG', 'KILOGRAMOS'),
    ('LT', 'LITROS'),
)

OPCIONES_APLICACION = (
    ('SC', 'SACOS'),
    ('CA', 'CANECAS'),
    ('LT', 'LITROS'),
    ('LB', 'LIBRAS'),
    ('KG', 'KILOS'),
    ('GR', 'GRAMOS'),
    ('ML', 'MILILITROS'),
)

OPCIONES_SUBCATEGORIA = (
    ('----------', '---------'),
    ('BALANCEADO', 'BALANCEADO'),
    ('CAL', 'CAL'),
    ('CERO FISH', 'CERO FISH'),
    ('MELAZA', 'MELAZA'),
    ('FERTILIZANTE', 'FERTILIZANTE'),
    ('MEDICAMENTO CAMARON', 'MEDICAMENTO CAMARON'),
    ('TRATAMIENTO AGUA', 'TRATAMIENTO AGUA'),
    ('TRATAMIENTO SUELO', 'TRATAMIENTO SUELO'),
    ('VITAMINA CAMARON', 'VITAMINA CAMARON'),
)

class ProductoForm(ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'
        widgets = {
            'nombre': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese un nombre',
                    'autocomplete': 'off'
                }
            ),
            'categoria': Select(
                attrs={
                    'class': 'form-control',
                    'autocomplete': 'off'
                }
            ),
            'gramaje': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese el Gramaje',
                    'autocomplete': 'off'
                }
            ),
            'descripcion': Select(choices=OPCIONES_SUBCATEGORIA,
                attrs={
                    'class': 'form-control'
                }
            ),
            'presentacion': Select(choices=OPCIONES_PRESENTACION,
                attrs={
                    'class': 'form-control'
                }
            ),
            'peso_presentacion': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese el Peso de la presentación',
                    'autocomplete': 'off'
                }
            ),
            'unid_medida': Select(choices=OPCIONES_MEDIDA,
                attrs={
                    'class': 'form-control'
                }
            ),
            'unid_aplicacion': Select(choices=OPCIONES_APLICACION,
                attrs={
                    'class': 'form-control'
                }
            ),
            'minimo_stock': NumberInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese un Stock Minimo',
                    'autocomplete': 'off'
                }
            ),
            'costo': NumberInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese su Costo',
                    'autocomplete': 'off'
                }
            )

            }

app_inventario/app_categoria/views/categoria.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from app_inventario.app_categoria.forms import CategoriaForm
from app_inventario.app_categoria.models import Categoria


# Lista basada en funcion
#def listarCategoria(request):
 #   data = {
 #       'nombre': 'Categoria',
 #       'categorias': Categoria.objects.all()
 #   }
 #   return render(request, 'app_inventario/app_categoria/categoria_listar.html', data)


#CREAREMOS EL INGRESO BASADO EN CLASES
class crearCategoriaView(CreateView):
    model = Categoria
    form_class = CategoriaForm
    template_name = 'app_inventario/app_categoria/categoria_crear.html'
    success_url = reverse_lazy('app_categoria:listar_categoria')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nombre'] = 'Ingresar Categoría'
        context['entity'] = 'Categoría'
        context['action'] = 'crear'
        return context


class actualizarCategoriaView(UpdateView):
    model = Categoria
    form_class = CategoriaForm
    template_name = 'app_inventario/app_categoria/categoria_crear.html'
    success_url = reverse_lazy('app_categoria:listar_categoria')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nombre'] = 'Actualizar Categoría'
        context['entity'] = 'Categoría'
        context['action'] = 'crear'
        return context


class eliminarCategoriaView(DeleteView):
    model = Categoria
    form_class = CategoriaForm
    template_name = 'app_inventario/app_categoria/categoria_eliminar.html'
    success_url = reverse_lazy('app_categoria:listar_categoria')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nombre'] = 'Eliminar Categoría'
        context['entity'] = 'Categoría'
        context['action'] = 'crear'
        return context


#CREAREMOS LISTA BASADA EN CLASES
class listarCategoriaView(ListView):
    # digo cual es el modelo o entidad en este caso categoria
    model = Categoria
    # defino la plantilla
    template_name = 'app_inventario/app_categoria/categoria_listar.html'


    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


    def post(self, request, *args, **kwargs):
        data = {}
        try:
            data = Categoria.objects.get(pk=request.POST['id']).toJSON()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)


    # defino el dicionario para enviar variables a mi plantilla
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #pongo el titulo a mi tabla y demas que necesiten
        context['nombre'] = 'Categoría'
        return context

app_inventario/app_categoria/views/producto.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from app_inventario.app_categoria.models import Categoria,Producto
from app_inventario.app_producto.forms import ProductoForm

def listarProducto(request):
    data = {
        'nombre': 'Producto',
        'categorias': Categoria.objects.all(),
        'productos': Producto.objects.all()
    }
    return render(request, 'app_inventario/app_producto/producto_listar.html', data)


# VISTA PARA CREAR EL PRODUCTO
class crearProductoView(CreateView):
    model = Producto
    form_class = ProductoForm
    template_name = 'app_inventario/app_producto/producto_crear.html'
    success_url = reverse_lazy('app_categoria:listar_producto')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nombre'] = 'Ingresar Producto'
        return context


# VISTAR PARA LISTAR EL PRODUCTO
class listarProductoView(ListView):
    # digo cual es el modelo o entidad en este caso categoria
    model = Producto
    # defino la plantilla
    template_name = 'app_inventario/app_producto/producto_listar.html'

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            data = Producto.objects.get(pk=request.POST['id']).toJSON()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    # defino el dicionario para enviar variables a mi plantilla
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #pongo el titulo a mi tabla y demas que necesiten
        context['nombre'] = 'Producto'
        context['categorias'] = Categoria.objects.all()
        context['productos'] = Producto.objects.all()
        return context


class actualizarProductoView(UpdateView):
    model = Producto
    form_class = ProductoForm
    template_name = 'app_inventario/app_producto/producto_crear.html'
    success_url = reverse_lazy('app_categoria:listar_producto')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nombre'] = 'Actualizar Producto'
        context['entity'] = 'Producto'
        context['action'] = 'crear'
        return context


class eliminarProductoView(DeleteView):
    model = Producto
    form_class = ProductoForm
    template_name = 'app_inventario/app_producto/producto_eliminar.html'
    success_url = reverse_lazy('app_categoria:listar_producto')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nombre'] = 'Eliminar Producto'
        context['entity'] = 'Producto'
        context['action'] = 'crear'
        return context

app_inventario/app_producto/views.py
from django.shortcuts import render

# Create your views here.

templates/app_inventario/app_categoria/categoria_crear.html
{% extends 'base.html' %}

{% load static %}

{% block contenido %}

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">{{ nombre }}</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">{{ nombre }}</a></li>
                        <li class="breadcrumb-item active">Registro {{ nombre }}</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <!-- Main content -->
    <form method="post" action=".">
        <section class="content">
            <div class="row">
                <div class="col-1">
                </div>
                <div class="col-10">
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header" style="background-color:#3498DB">
                            <h3 class="card-title">Opción:<strong> {{ nombre }}</strong></h3>
                        </div>

                        <!-- /.card-body -->
                        <div class="card-body">

                            {% csrf_token %}

                            {% for datos in form.visible_fields %}
                                <div class="form-group">
                                    <label for="nombre">{{ datos.label }}:</label>
                                    {{ datos }}
                                </div>
                            {% endfor %}

                        </div>

                        <div class="card-footer navbar-white">
                            <button type="submit" class="btn btn-primary btn-flat btnTest toastrDefaultSuccess">
                                <i class="fas fa-save"></i> GUARDAR
                            </button>
                            <a href="{% url 'app_categoria:listar_categoria' %}" class="btn btn-danger btn-file">
                                <i class="fas fa-times"></i> CANCELAR
                            </a>
                        </div>

                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
    </form>

    <!-- /.row -->
    <script type="application/javascript">

        {% if form.errors %}
            var errores = '';
            {% for field in form %}
                {% for error in field.errors %}
                    errores = '{{ error }}\n';
                {% endfor %}
            {% endfor %}
            Swal.fire({
                title: 'Error',
                text: errores,
                icon: 'error',
                confirmButtonText: 'OK'
            })
        {% endif %}

        {% comment %}$('form').on('submit', function (e) {
            e.preventDefault();
            alert('x');
        });
{% endcomment %}
    </script>

{% endblock %}


{% block scripts %}

    <script type="application/javascript">

        $(function () {
            $('.btnTest').on('click', function () {
                $.ajax({
                    url: '{% url 'app_categoria:listar_categoria' %}',
                    type: 'POST',
                    data: {id: 1},
                    dataType: 'json'
                }).done(function (data) {
                    Swal.fire({
                        position: 'top-end',
                        icon: 'success',
                        title: 'Información registrada correctamente',
                        showConfirmButton: false,
                        timer: 95000
                    });
                }).fail(function (data) {
                    toastr.error('Error verificar por favor', data)
                }).always(function (data) {
                    Swal.fire({
                        position: 'top-end',
                        icon: 'success',
                        title: 'Información registrada correctamente',
                        showConfirmButton: false,
                        timer: 95000
                    });
                })
            })
        })

        alert_jqueryconfirm();

    </script>

{% endblock %}

templates/app_inventario/app_categoria/categoria_eliminar.html
{% extends 'base.html' %}

{% load static %}

{% block contenido %}

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">{{ nombre }}</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">{{ nombre }}</a></li>
                        <li class="breadcrumb-item active">Eliminar {{ nombre }}</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <!-- Main content -->
    <form method="post" action=".">
        <section class="content">
            <div class="row">
                <div class="col-1">
                </div>
                <div class="col-10">
                    <!-- /.card -->
                    <div class="card ">
                        <div class="card-header" style="background-color:#3498DB">
                            <h3 class="card-title">Opción:<strong> {{ nombre }}</strong></h3>
                        </div>

                        <!-- /.card-body -->
                        <div class="card-body">

                            {% csrf_token %}

                            <div class="alert alert-default-danger alert-dismissible" style="text-align: center">

                                <h4><i class="icon fas fa-ban"> Notificacion:</i></h4>

                                <button class="alert alert-default-danger alert-dismissible btn btn-lg"
                                        style="text-align: center;height: 180px;width: 145px">
                                    <i class="fas fa-trash-alt fa-6x"></i>
                                </button>
                                </br></br>
                                <h4>
                                    Esta seguro de eliminar el registro </br>
                                    Id:<strong>&nbsp &nbsp{{ object.id }} </strong>
                                    &nbsp &nbsp - &nbsp &nbsp
                                    Nombre:<strong>&nbsp &nbsp{{ object.nombre }}</strong>
                                </h4>
                            </div>

                        </div>
                        <div class="card-footer navbar-white">
                            <button type="submit" class="btn btn-primary btn-flat btnTest toastrDefaultSuccess">
                                <i class="fas fa-check-circle"></i> SI, ACEPTAR
                            </button>
                            <a href="{% url 'app_categoria:listar_categoria' %}" class="btn btn-danger btn-file">
                                <i class="fas fa-times"></i> CANCELAR
                            </a>
                        </div>


                    </div>

                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
    </form>


{% endblock %}

{% block scripts %}

    <script type="application/javascript">
        $(function () {
            $('.btnTest').on('click', function () {
                $.ajax({
                    url: '{% url 'app_categoria:listar_categoria' %}',
                    type: 'POST',
                    data: {id: 1},
                    dataType: 'json'
                }).done(function (data) {

                }).fail(function (data) {
                    toastr.error('Error verificar por favor')
                }).always(function (data) {
                    toastr.info('Procesando datos')
                })
            })
        })
    </script>

{% endblock %}

templates/app_inventario/app_categoria/categoria_listar.html
{% extends 'base.html' %}

{% load static %}

{% block contenido %}

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="#">{{ nombre }}
                            <i class="far nav-icon fa fa-home"></i></a></li>
                        <li class="breadcrumb-item active">Listado de {{ nombre }}&nbsp
                            <i class="far nav-icon fa fa-clipboard-check"></i></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <!-- Main content -->

    <section class="content">
        <div class="row">
            <div class="col-12">

                <div class="card">
                    <div class="card-header" style="background-color:#3498DB">
                        <h3 class="card-title">Registros de: <strong> {{ nombre }}</strong></h3>
                        <div class="card-tools">
                            <ul class="pagination pagination-sm float-right">
                                <li class="page-item">
                                    <a href="{% url 'app_categoria:crear_categoria' %}"
                                       class="btn btn-block btn-default btn-sm">
                                        <strong><i class="fas fa-plus"></i> NUEVA CATEGORIA</strong>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="tb_categoria" class="table">
                            <thead>
                            <tr>
                                <th style="width: 5%;" class="text-center">Id</th>
                                <th style="width: 35%;">Nombre</th>
                                <th style="width: 50%;">Descripción</th>
                                <th style="width: 10%;" class="text-center">Opciones</th>
                            </tr>
                            </thead>
                            <tbody>

                            <!-- PONEMOS EL OBJETO DE LA PLANTILLA-->
                            {% for cate in object_list %}
                                <tr>
                                    <td class="text-center">{{ cate.id }} </td>
                                    <td>{{ cate.nombre }}</td>
                                    <td>{{ cate.descripcion }}</td>
                                    <td class="text-center">
                                        <div class="btn-group-sm">
                                            <a href="{% url 'app_categoria:actualizar_categoria' cate.id %}" class="btn-primary btn btn-xs">
                                                <i class="fas fa-edit"> </i>
                                            </a>
                                            <a href="{% url 'app_categoria:eliminar_categoria' cate.id %}" class="btn-danger btn btn-xs">
                                                <i class="fas fa-trash-alt"></i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}

                            </tbody>

                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.row -->

{% endblock %}

{% block scripts %}

    <script>
        $(function () {
            $("#tb_categoria").DataTable({
                "language": {
                    url: '{% static 'lib/datatables-1.10.20/spanish.txt' %}'
                },
                columnDefs: [{
                    orderable: false,
                    targets: [0, 1, 2, 3]
                }]
            });
        });
    </script>
{% endblock %}