Sistema_Camaronera/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from app_login.views.login import loginFormView
from app_template.views.template import IndexView

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', IndexView.as_view(),name='inicio_dashboard'),
    path('login/', include('app_login.urls')),
    path('inventario/', include('app_inventario.app_categoria.urls')),
    path('stock/', include('app_stock.app_detalle_stock.urls')),
    path('stock_directo/', include('app_stock_directo.urls')),
    path('empresa/', include('app_empresa.app_reg_empresa.urls')),
    path('dieta/', include('app_dieta.app_dieta_reg.urls')),
    path('seguimiento/', include('app_seglineal.app_seguimiento.urls')),
    path('factura/', include('app_factura_detalle.urls')),
    path('usuario/', include('app_user.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_dieta/app_dieta_reg/urls.py
from django.urls import path
from .views.dieta import *

app_name = 'app_dieta'

urlpatterns = [

    path('listar/anio/', listarDietaAnioPrincipalView.as_view(), name='principal_anio'),
    path('crear/anio/', crearAnioDietaView.as_view(), name='crear_anio_dieta'),

    #path('listar/mes/', listarDietaMesPrincipalView.as_view(), name='principal_mes'),
    path('listar/mes/<int:anio>/', listaDietas, name='principal_mes'),
    path('dieta/crear/mes/', crearMesDietaView.as_view(), name='crear_mes_dieta'),

    #path('listar/dia/<int:pk>/', listarDietaDiaPrincipalView.as_view(), name='principal_dia'),
    path('listar/dia/<int:pk>/', listarDias, name='principal_dia'),
    #path('crear/dia/<int:pk>/', crearDiaDieta, name='crear_dia_dieta'),
    path('crear/dia/<int:pk>/', crearDiaDietaView.as_view(), name='crear_dia_dieta'),
    #path('crear/dia/edit/', modificarDietas, name='modificar_dieta'),
    path('editar/dia/<int:pk>/', editarDiaDietaView.as_view(), name='modificar_dieta'),

    #path('dieta/crear/dia/registro/', crearRegistroDiaDietaView.as_view(), name='crear_registro_dia'),
    path('reporte_dieta/<int:pk>/', ListarDietaPDF.as_view(), name='reporte_dieta'),

    # PARA LAS DESCIPCIONES DE LAS DIETAS
    path('listar_desc_dieta/', listarDescripcionDietaView.as_view(), name='listar_descripcion_dieta'),
    path('crear_desc_dieta/', crearDescripcionDietaView.as_view(), name='crear_descripcion_dieta'),
    path('editar_desc_dieta/<int:pk>/', actualizarDescripcionDietaView.as_view(), name='editar_descripcion_dieta'),
    path('eliminar_desc_dieta/<int:pk>/', eliminarDescripcionDietaView.as_view(), name='eliminar_descripcion_dieta'),

]

app_seglineal/app_seguimiento/urls.py
from django.urls import path
from .views.segLineal import *


app_name = 'app_seguimiento'


urlpatterns = [

    path('listar', listarSeguimientoView.as_view(), name='listar_seguimiento'),
    path('listar/det_piscina/<int:pk>/', listarSeguimientoPiscinasView.as_view(), name='listar_seguimiento_det_piscina'),


]

app_user/urls.py
from django.urls import path
from .views.user import *

app_name = 'app_usuario'

urlpatterns = [

    path('usuario/crear/', crearUsuarioView.as_view(), name='crear_usuario'),
    path('usuario/actualizar/<int:pk>/', actualizarUsuarioView.as_view(), name='actualizar_usuario'),
    path('usuario/eliminar/<int:pk>/', eliminarUsuarioView.as_view(), name='eliminar_usuario'),
    path('usuario/listar/', listarUsuarioView.as_view(), name='listar_usuario')
]

app_seglineal/app_seguimiento/models.py
from django.db import models

# Create your models here.

app_seglineal/app_seguimiento/views/segLineal.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from app_empresa.app_reg_empresa.models import Piscinas
from app_stock.app_detalle_stock.models import Producto_Stock



# METODO PARA LISTAR LA VENTANA PRINCIPAL DEL SEGUIMIENTO
class listarSeguimientoView(ListView):
    model = Piscinas
    template_name = 'app_segLineal/segLineal_principal.html'

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            data = Producto_Stock.objects.get(pk=request.POST['id']).toJSON()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    # defino el dicionario para enviar variables a mi plantilla
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nombre'] = 'Seguimiento Lineal'
        context['seguimiento'] = Piscinas.objects.all()
        context['piscinas'] = Piscinas.objects.all()
        return context


# VENTANA PAR LISTAR EL SEGUIMIENTO POR DETALLES DE BUSQUEDA EJEMPLO: ID
class listarSeguimientoPiscinasView(ListView):
    model = Piscinas
    template_name = 'app_segLineal/segLineal_detalle.html'

    def get_queryset(self):
        return Piscinas.objects.filter(id=self.kwargs['pk'])

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            data = Piscinas.objects.get(id=self.kwargs['pk']).toJSON()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    # defino el dicionario para enviar variables a mi plantilla
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nombre'] = 'Kardex Stock Productos PSM'
        context['numero'] = Piscinas.objects.filter(id=self.kwargs['pk'])
        return context

templates/app_segLineal/segLineal_detalle.html
{% extends 'base.html' %}

{% load static %}

{% block head %}

    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/Seg_Lineal/css/jquery.dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/Seg_Lineal/css/searchPanes.dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/Seg_Lineal/css/select.dataTables.min.css' %}">

{% endblock %}

{% block contenido %}

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="#">{{ nombre }}&nbsp
                            <i class="far nav-icon fa fa-home"></i></a></li>
                        <li class="breadcrumb-item active"> Análisis por Piscinas&nbsp
                            <i class="far nav-icon fa fa-clipboard-check"></i></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <!-- Main content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">

                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header" style="background-color:#3498DB">
                            <h4 class="card-title"><strong>DETALLE POR PISCINAS: {{ object_list }}</strong></h4>
                            <div class="card-tools">
                                <a href="#"
                                   class="btn btn-md bg-gradient-white">
                                    <i class="fas fa-plus"></i> &nbsp AGREGAR
                                </a>
                                <a href="{% url 'app_seguimiento:listar_seguimiento' %}" class="btn btn-md bg-danger">
                                    <i class="fas fa-reply"></i> &nbsp REGRESAR
                                </a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-header">
                            <div class="card-body" style="height: 900px;">
                                <table id="tb_seguimiento" class="table" style="width:100%">
                                    <thead style="background-color:#3498DB">
                                    <tr>
                                        <th style="width: 5%;">Id</th>
                                        <th style="width: 15%;">Siglas Empresa</th>
                                        <th style="width: 20%;">Fecha Ingreso</th>
                                        <th style="width: 5%;">Cantidad</th>
                                        <th style="width: 10%;">N. Guia</th>
                                        <th style="width: 20%;">Producto</th>
                                        <th style="width: 20%;">Responsable</th>
                                        <th style="width: 5%;">Total</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    <!-- PONEMOS EL OBJETO DE LA PLANTILLA-->
                                    {% for reg in seguimiento %}
                                        <tr>
                                            <td style="text-align: center">{{ reg.id }}</td>
                                            <td style="text-align: center">{{ reg.producto_empresa.nombre_empresa.siglas }}</td>
                                            <td style="text-align: center">{{ reg.fecha_ingreso }}</td>
                                            <td style="text-align: center">{{ reg.cantidad_ingreso }}</td>
                                            <td style="text-align: center">{{ reg.cantidad_egreso }}</td>
                                            <td style="text-align: center">{{ reg.numero_guia }}</td>
                                            <td style="text-align: center">{{ reg.producto_empresa.nombre_prod }}</td>
                                            <td style="text-align: center">{{ reg.responsable_ingreso }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

                {% comment %}<div class="col-lg-2">
                    <div class="card">
                        <div class="card-header" style="background-color:#3498DB">
                            <h4 class="card-title"><strong>ANALISIS POR PISCINAS: </strong></h4>
                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                        class="fas fa-minus"></i></button>
                            </div>
                        </div>
                        <div class="card-body table-responsive p-0" style="height: 1030px;">
                            <table class="table table-head-fixed text-nowrap" id="tb_piscina">
                                <thead>
                                <tr>
                                    <th scope="col" style="width: 60%;">Piscinas</th>
                                    <th scope="col" style="width: 10%;">Ver</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for pis in piscinas %}
                                    <tr>
                                        <td>{{ pis.numero }}</td>
                                        <td>
                                            <a href="{% url 'app_seguimiento:listar_seguimiento_det_piscina' pis.orden %}"
                                               class="btn-primary btn btn-xs">
                                                <i class="fas fa-search"> </i>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>{% endcomment %}
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}

    <script src="{% static 'lib/datatables-1.10.20/Seg_Lineal/js/dataTables.searchPanes.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/Seg_Lineal/js/jquery-3.5.1.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/Seg_Lineal/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/Seg_Lineal/js/dataTables.select.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/Seg_Lineal/js/highcharts.js' %}"></script>

{#    <script src="{% static 'lib/datatables-1.10.20/Seg_Lineal/pdf/js/buttons.html5.min.js' %}"></script>#}
{#    <script src="{% static 'lib/datatables-1.10.20/Seg_Lineal/pdf/js/dataTables.buttons.min.js' %}"></script>#}
{#    <script src="{% static 'lib/datatables-1.10.20/Seg_Lineal/pdf/js/pdfmake.min.js' %}"></script>#}
{#    <script src="{% static 'lib/datatables-1.10.20/Seg_Lineal/pdf/js/vfs_fonts.js' %}"></script>#}

    <script src="{% static 'acciones/app_datatable/jquery/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'acciones/app_datatable/popper/popper.min.js' %}"></script>
    <script src="{% static 'acciones/app_datatable/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- datatables JS -->
    <script type="text/javascript" src="{% static 'acciones/app_datatable/datatables/datatables.min.js' %}"></script>
    <!-- para usar botones en datatables JS -->
    <script src="{% static 'acciones/app_datatable/datatables/Buttons-1.5.6/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'acciones/app_datatable/datatables/JSZip-2.5.0/jszip.min.js' %}"></script>
    <script src="{% static 'acciones/app_datatable/datatables/pdfmake-0.1.36/pdfmake.min.js' %}"></script>
    <script src="{% static 'acciones/app_datatable/datatables/pdfmake-0.1.36/vfs_fonts.js' %}"></script>
    <script src="{% static 'acciones/app_datatable/datatables/Buttons-1.5.6/js/buttons.html5.min.js' %}"></script>
    # PARA DETALLES DEL DATATABLE Y LA GRAFICA
    <script src="{% static 'acciones/app_seglineal/segProceso.js' %}"></script>

{% endblock %}

templates/app_segLineal/segLineal_principal.html
{% extends 'base.html' %}

{% load static %}

{% block contenido %}

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="#">{{ nombre }}&nbsp
                            <i class="far nav-icon fa fa-home"></i></a></li>
                        <li class="breadcrumb-item active">Listado de {{ nombre }}&nbsp
                            <i class="far nav-icon fa fa-clipboard-check"></i></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header" style="background-color:#3498DB">
                            <h4 class="card-title"><strong>SEGUIMIENTO LINEAL DE PISCINAS:</strong></h4>
                            {% comment %}<div class="card-tools">
                                <a href="{% url 'app_dieta:crear_anio_dieta' %}"  class="btn btn-block btn-default btn-sm">
                                    <strong><i class="fas fa-plus"></i> CREAR AÑO:</strong>
                                </a>
                            </div>{% endcomment %}
                        </div>

                        <div class="card-body">
                            <div class="row mt-6">
                                {% for data in object_list %}
                                <div class="col-md-2">

                                    <div class="card card-widget widget-user">
                                        <div class="widget-user-header bg-primary">
                                            <h2 class="widget-user-username"><strong> {{ data.numero }} </strong></h2>
                                            <h5 class="widget-user-desc">Empresa: {{ data.empresa.siglas }}</h5>
                                        </div>
                                        <div class="widget-user-image">
                                            <img class="img-circle elevation-2" src="{% static 'img/camaronsito.png' %}" alt="User Avatar">
                                        </div>
                                        <div class="card-footer">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="description-block">
                                                        <a href="{% url 'app_seguimiento:listar_seguimiento_det_piscina' data.id %}"
                                                           class="btn btn-sm btn-primary">
                                                            <i class="fas fa-search"> &nbsp Detalles</i>
                                                        </a>
                                                    </div>
                                                    <!-- /.description-block -->
                                                </div>
                                                <!-- /.col -->
                                            </div>
                                            <!-- /.row -->
                                        </div>
                                    </div>

                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}