Sistema_Camaronera/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from app_login.views.login import loginFormView
from app_template.views.template import IndexView

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', IndexView.as_view(),name='inicio_dashboard'),
    path('login/', include('app_login.urls')),
    path('inventario/', include('app_inventario.app_categoria.urls')),
    path('stock/', include('app_stock.app_detalle_stock.urls')),
    path('stock_directo/', include('app_stock_directo.urls')),
    path('empresa/', include('app_empresa.app_reg_empresa.urls')),
    path('dieta/', include('app_dieta.app_dieta_reg.urls')),
    path('seguimiento/', include('app_seglineal.app_seguimiento.urls')),
    path('factura/', include('app_factura_detalle.urls')),
    path('usuario/', include('app_user.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_dieta/app_dieta_reg/urls.py
from django.urls import path
from .views.dieta import *

app_name = 'app_dieta'

urlpatterns = [

    path('listar/anio/', listarDietaAnioPrincipalView.as_view(), name='principal_anio'),
    path('crear/anio/', crearAnioDietaView.as_view(), name='crear_anio_dieta'),

    #path('listar/mes/', listarDietaMesPrincipalView.as_view(), name='principal_mes'),
    path('listar/mes/<int:anio>/', listaDietas, name='principal_mes'),
    path('dieta/crear/mes/', crearMesDietaView.as_view(), name='crear_mes_dieta'),

    #path('listar/dia/<int:pk>/', listarDietaDiaPrincipalView.as_view(), name='principal_dia'),
    path('listar/dia/<int:pk>/', listarDias, name='principal_dia'),
    #path('crear/dia/<int:pk>/', crearDiaDieta, name='crear_dia_dieta'),
    path('crear/dia/<int:pk>/', crearDiaDietaView.as_view(), name='crear_dia_dieta'),
    #path('crear/dia/edit/', modificarDietas, name='modificar_dieta'),
    path('editar/dia/<int:pk>/', editarDiaDietaView.as_view(), name='modificar_dieta'),

    #path('dieta/crear/dia/registro/', crearRegistroDiaDietaView.as_view(), name='crear_registro_dia'),
    path('reporte_dieta/<int:pk>/', ListarDietaPDF.as_view(), name='reporte_dieta'),

    # PARA LAS DESCIPCIONES DE LAS DIETAS
    path('listar_desc_dieta/', listarDescripcionDietaView.as_view(), name='listar_descripcion_dieta'),
    path('crear_desc_dieta/', crearDescripcionDietaView.as_view(), name='crear_descripcion_dieta'),
    path('editar_desc_dieta/<int:pk>/', actualizarDescripcionDietaView.as_view(), name='editar_descripcion_dieta'),
    path('eliminar_desc_dieta/<int:pk>/', eliminarDescripcionDietaView.as_view(), name='eliminar_descripcion_dieta'),

]

app_user/urls.py
from django.urls import path
from .views.user import *

app_name = 'app_usuario'

urlpatterns = [

    path('usuario/crear/', crearUsuarioView.as_view(), name='crear_usuario'),
    path('usuario/actualizar/<int:pk>/', actualizarUsuarioView.as_view(), name='actualizar_usuario'),
    path('usuario/eliminar/<int:pk>/', eliminarUsuarioView.as_view(), name='eliminar_usuario'),
    path('usuario/listar/', listarUsuarioView.as_view(), name='listar_usuario')
]

app_dieta/app_dieta_reg/forms.py
from django.forms import *
from app_dieta.app_dieta_reg.models import AnioDieta, MesDieta, DiaDietaRegistro, DescripcionDieta, DetalleDiaDieta
from app_inventario.app_categoria.models import Producto


class AnioDietaForm(ModelForm):
    class Meta:
        model = AnioDieta
        fields = '__all__'
        widgets = {
            'anio_dieta': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese un Año',
                    'autocomplete': 'off'
                }
            )
        }


class MesDietaForm(ModelForm):
    class Meta:
        model = MesDieta
        fields = '__all__'
        widgets = {
            'mes_dieta': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese un Mes',
                    'autocomplete': 'off'
                }
            ),
            'fecha_dieta': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese un RUC',
                    'autocomplete': 'off'
                }
            ),
            'descripcion': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese una Descripciónx',
                    'autocomplete': 'off'
                }
            )

        }


class RegistroDiaDietaForm(ModelForm):
    class Meta:
        model = DiaDietaRegistro
        fields = '__all__'
        widgets = {
            'mes_dieta': Select(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese un Mes',
                    'autocomplete': 'off'
                }
            ),
            'fecha': DateInput(
                attrs={
                    'class': 'form-control',
                    'autocomplete': 'off'
                }
            )
        }


class DiaDietaForm(ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super(DiaDietaForm, self).__init__(*args, **kwargs)
    #     self.fields['insumo1'].queryset = Producto.objects.all()
    class Meta:
        model = DetalleDiaDieta
        fields = '__all__'
        widgets = {
            'fecha': DateInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese una Fecha',
                    'autocomplete': 'off'
                }
            ),
            'piscinas': Select(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese un RUC',
                    'autocomplete': 'off'
                }
            ),
            'balanceado': Select(
                attrs={
                    'class': 'form-control select2'
                }
            ),
            'insumo1': Select(
                attrs={
                    'class': 'form-control select2'
                }
            ),
            'insumo2': Select(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese una Descripción',
                    'autocomplete': 'off'
                }
            ),
            'insumo3': Select(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese una Descripción',
                    'autocomplete': 'off'
                }
            ),
            'insumo4': Select(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese una Descripción',
                    'autocomplete': 'off'
                }
            )

        }


class DescripcionDietaForm(ModelForm):
    class Meta:
        model = DescripcionDieta
        fields = '__all__'
        widgets = {
            'fecha': DateInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese un Año',
                    'autocomplete': 'off'
                }
            ),
            'descripcion': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese una Descripción',
                    'autocomplete': 'off'
                }
            )
        }

app_dieta/app_dieta_reg/views/dieta.py
# Create your views here.
import json
from django.db import transaction
import datetime
import decimal
from django.db import transaction
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.template.loader import get_template
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, View, UpdateView, DeleteView
from weasyprint import HTML
from app_dieta.app_dieta_reg.forms import AnioDietaForm, RegistroDiaDietaForm, DiaDietaForm, DescripcionDietaForm
from app_dieta.app_dieta_reg.models import MesDieta, AnioDieta, DiaDietaRegistro, DetalleDiaDieta, DescripcionDieta
from django.http import HttpResponse, Http404, JsonResponse, HttpResponseRedirect
# Para crear las Dietas
from app_empresa.app_reg_empresa.models import Empresa, Piscinas
from app_inventario.app_categoria.models import Producto
from app_reportes.utils import render_to_pdf
from app_stock.app_detalle_stock.models import Producto_Stock, Total_Stock


class crearAnioDietaView(CreateView):
    model = AnioDieta
    form_class = AnioDietaForm
    template_name = 'app_dieta/dieta_principal_anio_crear.html'
    success_url = reverse_lazy('app_dieta:principal_anio')

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nombre'] = 'Dieta'
        return context


class crearMesDietaView(CreateView):
    model = MesDieta
    template_name = 'app_dieta/dieta_principal_mes_crear.html'
    success_url = reverse_lazy('app_dieta:principal_mes')

    @method_decorator(csrf_exempt)
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nombre'] = 'Dieta'
        return context


def modificarDietas(request):
    print(request)
    if request.POST:
        id_dieta = int(request.POST.get('id'))
        dieta_registro = DetalleDiaDieta.objects.get(id=id_dieta)
        # dieta_registro.dieta_id=request.POST.get('dieta')
        # dieta_registro.piscinas_id = request.POST.get('piscinas')

        id_balanceado = int(request.POST.get('balanceado'))
        cantidad = decimal.Decimal(request.POST.get('cantidad').replace(",", "."))
        if id_balanceado != dieta_registro.balanceado.pk or cantidad != dieta_registro.cantidad:
            if id_balanceado > 0:
                # Realizo el rollback (se suma el stock del producto que se actualizó)
                ps = Total_Stock.objects.get(nombre_empresa_id=dieta_registro.piscinas.empresa.pk,
                                             nombre_prod_id=dieta_registro.balanceado.pk)
                ps.stock = ps.stock + dieta_registro.cantidad
                ps.save()

                producto = Producto_Stock.objects.filter(piscinas=dieta_registro.piscinas.numero,
                                                         producto_empresa_id=ps.pk)
                producto.delete()

                dieta_registro.balanceado_id = id_balanceado
                dieta_registro.cantidad = cantidad

        insumo1 = int(request.POST.get('insumo1'))
        gramaje1 = decimal.Decimal(request.POST.get('gramaje1'))
        if insumo1 != dieta_registro.insumo1 or gramaje1 != dieta_registro.gramaje1:
            if insumo1 > 0:
                # Realizo el rollback (se suma el stock del producto que se actualizó)
                ps = Total_Stock.objects.get(nombre_empresa_id=dieta_registro.piscinas.empresa.pk,
                                             nombre_prod_id=dieta_registro.insumo1)
                ps.stock = ps.stock + dieta_registro.gramaje1
                ps.save()

                producto = Producto_Stock.objects.filter(piscinas=dieta_registro.piscinas.numero,
                                                         producto_empresa_id=ps.pk)
                producto.delete()

                dieta_registro.insumo1 = insumo1
                dieta_registro.gramaje1 = gramaje1

        insumo2 = int(request.POST.get('insumo2'))
        gramaje2 = decimal.Decimal(request.POST.get('gramaje2'))
        if insumo2 != dieta_registro.insumo2 or gramaje2 != dieta_registro.gramaje2:
            if insumo2 > 0:
                # Realizo el rollback (se suma el stock del producto que se actualizó)
                ps = Total_Stock.objects.get(nombre_empresa_id=dieta_registro.piscinas.empresa.pk,
                                             nombre_prod_id=dieta_registro.insumo2)
                ps.stock = ps.stock + dieta_registro.gramaje2
                ps.save()

                producto = Producto_Stock.objects.filter(piscinas=dieta_registro.piscinas.numero,
                                                         producto_empresa_id=ps.pk)
                producto.delete()

                dieta_registro.insumo2 = insumo2
                dieta_registro.gramaje2 = gramaje2

        insumo3 = int(request.POST.get('insumo3'))
        gramaje3 = decimal.Decimal(request.POST.get('gramaje3'))
        if insumo3 != dieta_registro.insumo3 or gramaje3 != dieta_registro.gramaje3:
            if insumo3 > 0:
                # Realizo el rollback (se suma el stock del producto que se actualizó)
                ps = Total_Stock.objects.get(nombre_empresa_id=dieta_registro.piscinas.empresa.pk,
                                             nombre_prod_id=dieta_registro.insumo3)
                ps.stock = ps.stock + dieta_registro.gramaje3
                ps.save()

                producto = Producto_Stock.objects.filter(piscinas=dieta_registro.piscinas.numero,
                                                         producto_empresa_id=ps.pk)
                producto.delete()

                dieta_registro.insumo3 = insumo3
                dieta_registro.gramaje3 = gramaje3

        insumo4 = int(request.POST.get('insumo4'))
        gramaje4 = decimal.Decimal(request.POST.get('gramaje4'))
        if insumo4 != dieta_registro.insumo4 or gramaje4 != dieta_registro.gramaje4:
            if insumo4 > 0:
                # Realizo el rollback (se suma el stock del producto que se actualizó)
                ps = Total_Stock.objects.get(nombre_empresa_id=dieta_registro.piscinas.empresa.pk,
                                             nombre_prod_id=dieta_registro.insumo4)
                ps.stock = ps.stock + dieta_registro.gramaje4
                ps.save()

                producto = Producto_Stock.objects.filter(piscinas=dieta_registro.piscinas.numero,
                                                         producto_empresa_id=ps.pk)
                producto.delete()

                dieta_registro.insumo4 = insumo4
                dieta_registro.gramaje4 = gramaje4
        dieta_registro.save()
        return HttpResponse("Se registro MODIFICAR DIETA..!")


# def modificarDietas(request):
#     if request.POST:
#         dieta_registro=DetalleDiaDieta.objects.get(id=request.POST.get('id'))
#         dieta_registro.dieta_id=request.POST.get('dieta')
#         dieta_registro.piscinas_id = request.POST.get('piscinas')
#         if int(request.POST.get('balanceado'))>0:
#             dieta_registro.balanceado_id = request.POST.get('balanceado')
#             dieta_registro.cantidad = request.POST.get('cantidad').replace(",",".")
#         if int(request.POST.get('insumo1'))>0:
#             dieta_registro.insumo1 = request.POST.get('insumo1')
#             dieta_registro.gramaje1 = request.POST.get('gramaje1')
#         if int(request.POST.get('insumo2')) > 0:
#             dieta_registro.insumo2 = request.POST.get('insumo2')
#             dieta_registro.gramaje2 = request.POST.get('gramaje2')
#         if int(request.POST.get('insumo3')) > 0:
#             dieta_registro.insumo3 = request.POST.get('insumo3')
#             dieta_registro.gramaje3 = request.POST.get('gramaje3')
#         if int(request.POST.get('insumo4')) > 0:
#             dieta_registro.insumo4 = request.POST.get('insumo4')
#             dieta_registro.gramaje4 = request.POST.get('gramaje4')
#         dieta_registro.save()
#         return HttpResponse("Se registro MODIFICAR DIETA..!")


def crearDiaDieta(request, pk):
    productos = Producto.objects.all()
    if request.POST:
        dieta_registro = DetalleDiaDieta()
        dieta_registro.dieta_id = request.POST.get('dieta')
        dieta_registro.piscinas_id = request.POST.get('piscinas')
        with transaction.atomic():
            if int(request.POST.get('balanceado')) > 0:
                dieta_registro.balanceado_id = request.POST.get('balanceado')
                dieta_registro.cantidad = request.POST.get('cantidad')
            if int(request.POST.get('insumo1')) > 0:
                dieta_registro.insumo1 = request.POST.get('insumo1')
                dieta_registro.gramaje1 = request.POST.get('gramaje1')
            if int(request.POST.get('insumo2')) > 0:
                dieta_registro.insumo2 = request.POST.get('insumo2')
                dieta_registro.gramaje2 = request.POST.get('gramaje2')
            if int(request.POST.get('insumo3')) > 0:
                dieta_registro.insumo3 = request.POST.get('insumo3')
                dieta_registro.gramaje3 = request.POST.get('gramaje3')
            if int(request.POST.get('insumo4')) > 0:
                dieta_registro.insumo4 = request.POST.get('insumo4')
                dieta_registro.gramaje4 = request.POST.get('gramaje4')
            dieta_registro.save()
            return HttpResponse("Se registro CREAR DIETA..!")
    contexto = {

templates/app_dieta/dieta_principal_anio.html
{% extends 'base.html' %}

{% load static %}

{% block contenido %}

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="#">{{ nombre }}&nbsp
                            <i class="far nav-icon fa fa-home"></i></a></li>
                        <li class="breadcrumb-item active">Listado de {{ nombre }}&nbsp
                            <i class="far nav-icon fa fa-clipboard-check"></i></li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header" style="background-color:#3498DB">
                            <div class="card-tools">
                                <a href="{% url 'app_dieta:crear_anio_dieta' %}"  class="btn btn-block btn-default btn-sm">
                                    <strong><i class="fas fa-plus"></i> CREAR AÑO:</strong>
                                </a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <div class="row mt-6">
                                {% for data in object_list %}
                                    <div class="col-12 col-sm-6 col-md-2 d-flex align-items-stretch">
                                        <div class="card bg-light">
                                            <div class="card-header text-muted border-bottom-0">
                                            </div>
                                            <div class="card-body">
                                                <div class="row">
                                                    <div class="col-7 text-center">
                                                        <h2 class="lead"><strong><b>Año: {{ data.anio_dieta }}</b></strong></h2>
                                                        <p class="text-muted text-sm text-center">
                                                            <b>Registro y Control</b>
                                                            <b>Dietas Diarias</b>
                                                        </p>
                                                    </div>
                                                    <div class="col-5 text-center">
                                                        <img src="{% static 'img/camaronsito.png' %}" alt=""
                                                             class="img-circle img-fluid">
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="card-footer">
                                                <div class="text-center">
                                                    <a href="{% url 'app_dieta:principal_mes' data.id %}"
                                                       class="btn btn-sm btn-primary">
                                                        <i class="fas fa-plus"></i> Ver
                                                    </a>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                {% endfor %}

                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.row -->

{% endblock %}

templates/app_dieta/dieta_principal_mes.html
{% extends 'base.html' %}

{% load static %}

{% block contenido %}

    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <ol class="breadcrumb float-sm-left">
                        <li class="breadcrumb-item"><a href="#">{{ nombre }}&nbsp
                            <i class="far nav-icon fa fa-home"></i></a>
                        </li>
                        <li class="breadcrumb-item active">Listado de {{ nombre }}&nbsp
                            <i class="far nav-icon fa fa-clipboard-check"></i>
                        </li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <!-- Main content -->

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header" style="background-color: #0d8ddb">
                            <div class="card-tools">
                                <a href="#" id="crear" data-toggle="modal" data-target="#modal_crear_mes"
                                   class="btn btn-md bg-teal">
                                    <i class="fas fa-plus"></i> Crear Mes
                                </a>
                                <a href="{% url 'app_dieta:principal_anio' %}" class="btn btn-md bg-danger">
                                    <i class="fas fa-reply"></i> Regresar
                                </a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">

                            <div class="row mt-6">
                                {% for mes in meses %}
                                    <div class="col-12 col-sm-6 col-md-3 d-flex align-items-stretch">
                                        <div class="card bg-light">
                                            <div class="card-header text-muted border-bottom-0">
                                            </div>
                                            <div class="card-body">
                                                <div class="row">
                                                    <div class="col-8">
                                                        <h2 class="lead"><b><strong> {{ mes.mes_dieta }}
                                                            DEL {{ mes.anio.anio_dieta }}</strong></b></h2>
                                                        <p class="text-muted text-sm">
                                                            <b><strong>CONTROL Y ELABORACIÓN DE DIETAS DEL MES: </strong></b>
                                                            </br>
                                                            {{ mes.descripcion }}
                                                        </p>
                                                    </div>
                                                    <div class="col-4 text-center">
                                                        <img src="{% static 'img/camaronsito.png' %}" class="img-circle img-fluid"
                                                             style="width: 120px; height: 100px;">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="card-footer">
                                                <div class="text-center">
                                                    <a href="{% url 'app_dieta:principal_anio' %}"
                                                       class="btn btn-sm btn-danger">
                                                        <i class="fas fa-reply"></i>
                                                    </a>
                                                    <a href="#" data-toggle="modal" data-id="{{ mes.id }}" data-mes="{{ mes.mes_dieta }}" data-descripcion="{{ mes.descripcion }}" data-target="#modal_crear_mes" class="btn btn-sm btn-info edit">
                                                        <i class="fas fa-edit"></i>
                                                    </a>
                                                    <a href="{% url 'app_dieta:principal_dia' mes.id %}"
                                                       class="btn btn-sm btn-primary">
                                                        <i class="fas fa-file-alt"></i>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                {% endfor %}

                            </div>


                            <!-- Default box -->

                            <!-- /.card -->


                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.row -->
    <!-- /.modal_crear_mes -->
    <div class="modal fade" id="modal_crear_mes">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Crear Mes</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal" id="crear_mes" method="post">
                        {% csrf_token %}
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="anio" class="col-sm-2 col-form-label">Año *</label>
                                <div class="col-sm-10">
                                    <input type="text" value="{{ anio }}" readonly="readonly" class="form-control" id="anio" name="anio" placeholder="Ingrese el Año">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="mes_dieta" class="col-sm-2 col-form-label">Mes Dieta</label>
                                <div class="col-sm-10">
                                    <select name="mes_dieta" id="mes_dieta" class="form-control">
                                        <option value="ENERO">Enero</option>
                                        <option value="FEBRERO">Febrero</option>
                                        <option value="MARZO">Marzo</option>
                                        <option value="ABRIL">Abril</option>
                                        <option value="MAYO">Mayo</option>
                                        <option value="JUNIO">Junio</option>
                                        <option value="JULIO">Julio</option>
                                        <option value="AGOSTO">Agosto</option>
                                        <option value="SEPTIEMBRE">Septiembre</option>
                                        <option value="OCTUBRE">Octubre</option>
                                        <option value="NOVIEMBRE">Noviembre</option>
                                        <option value="DICIEMBRE">Diciembre</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="descripcion" class="col-sm-2 col-form-label">Descripción *</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" required="required" id="descripcion" name="descripcion" placeholder="Ingrese la descripción">
                                </div>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Registrar</button>
                            <button type="reset" class="btn btn-default" data-dismiss="modal">Salir</button>
                        </div>
                        <!-- /.card-footer -->
                    </form>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->

{% endblock %}


{% block scripts %}
    <script>
        $('#crear').click(function(){
            $("#crear_mes").attr('action','{% url 'app_dieta:principal_mes' anio.id %}?nuevo=nuevo')
            $("#mes_dieta").removeAttr('readonly')
        });
        $('.edit').click(function(){
            $("#crear_mes").attr('action','{% url 'app_dieta:principal_mes' anio.id %}?mes='+$(this).data('id'))
            $("#descripcion").val($(this).data('descripcion'))
            $("#mes_dieta").val($(this).data('mes'))
            $("#mes_dieta").attr('readonly','readonly')
        })
    </script>
{% endblock %}